import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Grocery Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="min-content fixed w-full px-5 py-10 sm:px-32">
        <nav className="flex flex-row items-center justify-between ">
          <h1
            className={`${styles.title} text-4xl font-bold tracking-tight sm:text-6xl`}
          >
            <span className="text-primary">GROCERY</span>
            <span className="text-accent">MATE</span>
          </h1>
          <button>
            <svg viewBox="0 0 100 80" width="40" height="40" fill="#453c38">
              <rect width="100" height="15" rx="5"></rect>
              <rect y="30" width="100" height="15" rx="5"></rect>
              <rect y="60" width="100" height="15" rx="5"></rect>
            </svg>
          </button>
          {/* <div className="min-w-[600px] space-x-10">
            <input
              className="rounded-full border border-gray-400 bg-white/50 p-2 shadow-lg"
              placeholder="Find a recipe"
            />
            <a>Browse Recipes</a>
            <a>Sign up</a>
            <a>Log in</a>
          </div> */}
        </nav>
      </header>

      <main className="w-full">
        <div className="grid justify-between sm:grid-cols-2">
          <div className="self-center pl-32">
            <h1 className="font-bold text-primary sm:text-7xl">
              Automate your online grocery shopping experience
            </h1>
            <p>
              Choose your recipes for the week and add the ingredients to your
              Kroger cart in one click
            </p>
            <button>Browse 1000+ Recipes</button>
            <button>Create Your Own Recipe</button>
          </div>
          <img className="" src="./brooke-lark-RrzeCGujVfU-unsplash.jpg" />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
