import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const handleNav = () => {
    setIsOpen(!isOpen);
  };

  return (
    <div className={isOpen ? "h-screen overflow-hidden" : "overflow-y-clip"}>
      <Head>
        <title>Grocery Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="z-50 flex w-full justify-between p-5">
        <h1
          className={`${styles.title}  w-1/2 text-5xl font-bold tracking-tight sm:text-6xl`}
        >
          <span className="text-primary">GROCERY</span>
          <span className="text-accent">MATE</span>
        </h1>
        <button
          onClick={handleNav}
          className=" z-20 content-end sm:hidden"
          aria-controls="primary-navigation"
          aria-expanded={isOpen}
        >
          <svg viewBox="0 0 100 80" width="20" height="20" fill="#453c38">
            <rect width="100" height="20" rx="10"></rect>
            <rect y="30" width="100" height="20" rx="10"></rect>
            <rect y="60" width="100" height="20" rx="10"></rect>
          </svg>
          <span className="sr-only">Menu</span>
        </button>
        <nav
          id="primary-navigation"
          data-visible={isOpen}
          className="absolute top-0 right-0 bottom-0 left-1/2 z-0 flex flex-col space-y-8 bg-white px-5 py-20 text-center "
        >
          <div className="flex w-full flex-row rounded-full border-2 border-gray-200 bg-white/50 p-2 transition duration-300 ease-in focus-within:border-accent focus-within:transition focus-within:duration-300 focus-within:ease-in">
            <input
              className="w-full px-2 placeholder:text-sm focus:outline-none"
              placeholder="Find a recipe"
              aria-label="Search"
            />
            <button className="h-[20px] min-w-[20px] self-center pr-2 focus:outline-none">
              <img className="" src="./magnifying-glass-svgrepo-com.svg"></img>
            </button>
          </div>
          <a>Browse All Recipes</a>
          <a>Sign Up</a>
          <a>Log in</a>
        </nav>
      </header>

      <main className="">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt alias
        fuga commodi labore suscipit ipsum, nesciunt, nemo sint atque,
        accusantium unde. Aperiam, vel? Vero voluptas alias perferendis! Non,
        quaerat provident! Ex molestias dolorem enim eum perferendis obcaecati
        quis, sed quasi in. Molestiae provident eligendi, placeat ipsa,
        perspiciatis laboriosam aut illo cum possimus eveniet deserunt delectus
        optio sed quod voluptate corporis. Sequi dignissimos soluta, ea
        temporibus minus laborum eum id aliquid fugiat, eos repellendus? Quidem
        necessitatibus, quaerat rerum error reiciendis architecto magnam optio
        nostrum delectus explicabo earum cum quod maxime autem? Ipsam ullam sint
        id voluptas exercitationem cupiditate possimus rerum facilis aspernatur
        officia libero, voluptate repellendus dolor architecto, labore dolore
        assumenda numquam inventore ipsum corrupti tempore qui quaerat! Tenetur,
        voluptate veritatis! Eligendi, praesentium. Voluptatum fugit harum
        perferendis exercitationem hic magni ducimus tempora consequatur sunt
        libero iusto excepturi, debitis quia ut tenetur dolores? Nam, velit illo
        quam dolorem iusto iure incidunt quisquam! Reiciendis, nemo aspernatur
        adipisci quo aperiam error nam dolorem neque eligendi corrupti
        voluptatem suscipit tempora rem, quod sed. Voluptates hic similique quae
        aspernatur labore amet sunt assumenda dolor dignissimos quas. Sapiente
        nostrum ut exercitationem aspernatur deleniti commodi dolore praesentium
        recusandae ex magnam ullam maxime consectetur minima blanditiis
        obcaecati, reiciendis aut fugiat error dolor earum quo fuga. Molestiae
        atque dolorem sequi! Ad quaerat iste, accusamus expedita ducimus cumque
        similique, consectetur optio incidunt ipsam libero, voluptatem sit atque
        voluptatum qui! Amet reprehenderit nulla molestiae odit, impedit modi
        voluptate expedita ipsa quas quo? Lorem ipsum dolor sit amet consectetur
        adipisicing elit. Facilis nesciunt enim non officia ducimus rerum
        accusamus distinctio in nisi quibusdam, quam dolorem aspernatur
        reiciendis et alias, omnis ipsam? Ratione, tenetur. Necessitatibus dolor
        doloremque dignissimos! Veniam alias fugit odio reprehenderit accusamus
        sapiente consequuntur cupiditate, blanditiis, eaque est excepturi quae!
        Laborum unde vero accusamus similique pariatur laboriosam illo aliquam
        iste perferendis eveniet! Porro doloremque ullam vitae dolore at atque
        commodi iusto iure minima, molestias vero qui voluptate sed possimus
        quos nulla quasi pariatur beatae nobis laborum, labore error placeat
        repellat dolorem. Aperiam. Tenetur quos ad commodi velit doloremque,
        sunt nisi amet vitae sapiente veritatis neque id tempore quod vero,
        pariatur ipsam omnis mollitia fugiat quaerat voluptates recusandae
        dolore! Harum quidem consequatur expedita. Qui officiis delectus hic
        expedita voluptates deserunt corrupti sit consequuntur, impedit optio,
        quae magnam dolorum minus magni! Eveniet ipsam magni excepturi accusamus
        suscipit vero et nostrum, numquam laboriosam enim pariatur. Qui dolores
        corrupti corporis aut commodi aliquid maiores quae accusamus. Sit,
        provident! Eligendi perspiciatis eveniet tempora magnam obcaecati
        molestias consectetur qui perferendis dolore, libero voluptates, rem
        voluptatum, quisquam aut explicabo!
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
